# sc-nfs.yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.2.20
  share: /share/CACHEDEV1_DATA/docker01
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nolock
  - nfsvers=3
