apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: media
  name: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 100Mi
