apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: tika
  name: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tika
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/paperless-default: "true"
        io.kompose.service: tika
    spec:
      containers:
        - image: ghcr.io/paperless-ngx/tika:latest
          name: tika
      restartPolicy: Always
