apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: webserver-claim2
  name: webserver-claim2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 100Mi
