apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: homebridge-claim0
  name: homebridge-claim0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 100Mi
