apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: homebridge
  name: homebridge
spec:
  type: NodePort
  ports:
    - port: 8581
      nodePort: 30005
  selector:
    io.kompose.service: homebridge
